CREATE TABLE IF NOT EXISTS `access_token` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `client_id` VARCHAR(255) NOT NULL,
    `api_key` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
