CREATE TABLE IF NOT EXISTS `tbl_reservation_cloudbed` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `property_id` VARCHAR(32) NOT NULL,
    `reservation_id` VARCHAR(32) NOT NULL,
    `date_created` DATETIME NOT NULL,
    `date_modified` DATETIME NOT NULL,
    `status` VARCHAR(50) NOT NULL,
    `guest_id` VARCHAR(32) NOT NULL,
    `profile_id` VARCHAR(32) NOT NULL,
    `guest_name` VARCHAR(255) NOT NULL,
    `start_date` DATE NOT NULL,
    `end_date` DATE NOT NULL,
    `adults` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `children` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `balance` BIGINT NOT NULL DEFAULT 0,
    `source_id` VARCHAR(50) NOT NULL,
    `source_name` VARCHAR(100) NOT NULL,
    `room_type_name` VARCHAR(255) DEFAULT NULL,
    `room_name` VARCHAR(255) DEFAULT NULL,
    `third_party_identifier` VARCHAR(255) DEFAULT NULL,
    `allotment_block_code` VARCHAR(100) DEFAULT NULL,
    `group_code` VARCHAR(100) DEFAULT NULL,
    `origin` VARCHAR(100) DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_reservation_reservation_id` (`reservation_id`),
    KEY `idx_reservation_property_id` (`property_id`),
    KEY `idx_reservation_guest_id` (`guest_id`),
    KEY `idx_reservation_profile_id` (`profile_id`),
    KEY `idx_reservation_start_date` (`start_date`),
    KEY `idx_reservation_end_date` (`end_date`),
    KEY `idx_reservation_room_name` (`room_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
